name: Build workflow

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lk-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Install pyhton2
      run: sudo apt-get install python2
    - name: Build the bootloader
      run: |
        export python=python2
        make X5
    - name : Upload bootloader
      uses: actions/upload-artifact@v2
      with:
        name: X5_lk-signed.img
        path: /home/runner/work/lk/lk/build-X5/lk-sign.img
